idf_component_register(
    SRCS
        "app_main.cpp"
        "Common/ESPNow.cpp"
        "Common/wifi_init.c"
        "Common/Frame.cpp"
        "Leader/Forward_K.cpp"
        "Leader/Leader.cpp"
        "Primary/Primary.cpp"
        "Follower/Follower.cpp"
        "ServoCommunication/ServoCommunication.cpp"
    INCLUDE_DIRS
        "."
        "Common"
        "Leader"
        "Primary"
        "Follower"
        "ServoCommunication"
    REQUIRES
        esp_wifi
        esp_event
        esp_netif
        freertos
        esp_driver_uart
        esp_driver_usb_serial_jtag
        nvs_flash
        esp_driver_gpio
)
